server:
  port: 8080

spring:
  application:
    name: resource-server

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_SERVER_JWKS_URI:http://localhost}
          issuer-uri: ${AUTH_SERVER_ISSUER_URI:http://localhost}
          audiences: ${AUTH_SERVER_AUD:http://localhost}


logging:
  level:
    org.springframework.security: DEBUG